version: "3.9"
services:
  vue:
    build:
      context: ./vue
    container_name: vue_frontend
    ports:
      - ${QUASAR_PORT}:${QUASAR_PORT}
    volumes:
      - ./vue:/vue
      - /vue/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 1
      CRAWLER_BASE_URL: http://localhost:5000/api/v1

  postgres:
    image: postgres:12
    container_name: postgres_db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: web_crawler

  crawler:
    build:
      context: ./crawler
      target: development
    container_name: crawler
    ports:
      - ${CRAWLER_PORT}:${CRAWLER_PORT}
    volumes:
      - ./crawler:/usr/src/app # creates host 
      - /usr/src/app/node_modules # this prevents node_modules to be copied to the container during build
      - /usr/src/app/crawler_engine
      - /usr/src/app/bin
      # https://burnedikt.com/dockerized-node-development-and-mounting-node-volumes/ todo: read this
    command: npm run dev
    environment:
          CRAWLER_PORT: ${CRAWLER_PORT}
          HASURA_ENDPOINT_URL: http://hasura:8080/v1/graphql
          CRAWLER_EXE_LOCATION: /usr/src/app/bin/crawler_engine

  hasura:
    build:
      context: ./hasura
    container_name: hasura_graphql
    ports:
    - ${HASURA_PORT}:${HASURA_PORT}
    depends_on:
    - "postgres"
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://root:toor@postgres:5432/web_crawler
      HASURA_GRAPHQL_DATABASE_URL: postgres://root:toor@postgres:5432/web_crawler
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://root:toor@postgres:5432/web_crawler
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
